import 'package:cm_app/core/models/movie.dart';
import 'package:cm_app/core/models/show.dart';

final movies = [
  Movie(
    id: 25748,
    title: 'The Trepidation: Deadest Night',
    year: '2026',
    rating: '3.9',
    poster: 'https://media.homietv.com/file/all-asset-uploads/cm-app-media-two/movies/2026-08-26/mUAwbdfbXxjTw1S3diSEYpRrd3F.jpg',
    genres: ['Horror'],
  ),
  Movie(
    id: 25749,
    title: 'Patton',
    year: '1970',
    rating: '7.4',
    poster: 'https://media.homietv.com/file/all-asset-uploads/cm-app-media-two/movies/2026-08-26/rLM7jIEPTjj4CF7F1IrzzNjLUCu.jpg',
    genres: ['Drama', 'History', 'War'],
  ),
  Movie(
    id: 25747,
    title: 'Pluto',
    year: '2026',
    rating: '0.0',
    poster: 'https://media.homietv.com/file/all-asset-uploads/cm-app-media-two/movies/2026-08-26/pPxsw4KnZbsklyHUCTKSCHKaC8F.jpg',
    genres: ['Comedy', 'Science Fiction'],
  ),
  Movie(
    id: 25746,
    title: 'The Sheriff',
    year: '2026',
    rating: '6.2',
    poster: 'https://media.homietv.com/file/all-asset-uploads/cm-app-media-two/movies/2026-08-26/pba15JjYAoyuFIM6kkZ7qE6oqG2.jpg',
    genres: ['Action', 'Crime'],
  ),
  Movie(
    id: 25186,
    title: 'Once Upon a Time in a Battlefield',
    year: '2003',
    rating: '6.7',
    poster: 'https://media.homietv.com/file/all-asset-uploads/cm-app-media-two/movies/2026-07-07/2Th2BQwuxSrh37p8wWG7y61uq5W.jpg',
    genres: ['Comedy', 'History', 'War'],
  ),
  Movie(
    id: 25745,
    title: 'Dil To Pagal Hai',
    year: '1997',
    rating: '6.9',
    poster: 'https://media.homietv.com/file/all-asset-uploads/cm-app-media-two/movies/2026-08-25/HKUrZZbXnwCM4129fPlgHEg0eG.jpg',
    genres: ['Comedy', 'Drama', 'Romance'],
  ),
  Movie(
    id: 25744,
    title: 'Pinocchio: Unstrung',
    year: '2026',
    rating: '7.0',
    poster: 'https://media.homietv.com/file/all-asset-uploads/cm-app-media-two/movies/2026-08-25/eUJXk3bTvLBi5Zcb0BCedZU7lVL.jpg',
    genres: ['Fantasy', 'Horror', 'Mystery'],
  ),
  Movie(
    id: 25733,
    title: 'Batman: Knightfall Part 1',
    year: '2026',
    rating: '7.2',
    resolution: '4K',
    poster: 'https://media.homietv.com/file/all-asset-uploads/cm-app-media-two/movies/2026-08-25/g19IoButQepcHPShmzfPGYOWfTq.jpg',
    genres: ['Action', 'Adventure', 'Animation'],
  ),
  Movie(
    id: 25743,
    title: 'I Am a Hero',
    year: '2016',
    rating: '7.4',
    poster: 'https://media.homietv.com/file/all-asset-uploads/cm-app-media-two/movies/2026-08-25/4RnmHtCLtbBHD9jagVlcSzJTWX6.jpg',
    genres: ['Action', 'Drama', 'Horror'],
  ),
  Movie(
    id: 25740,
    title: 'I, Nobody',
    year: '2026',
    rating: '6.0',
    poster: 'https://media.homietv.com/file/all-asset-uploads/cm-app-media-two/movies/2026-08-25/qFJl3w9KpVXpfZ3rpmv7p0UYZkP.jpg',
    genres: ['Crime', 'Drama', 'Thriller'],
  ),
];

final shows = [
  Show(
    title: 'Reacher',
    year: '2022',
    rating: '8.1',
    seasons: 1,
    poster: 'https://media.homietv.com/file/all-asset-uploads/cm-app-media-two/tv-shows/2026-08-12/f1VCQIG2iCyOookdgOzwtUpwWC0.jpg',
    genres: ['Action & Adventure', 'Crime', 'Drama'],
  ),
  Show(
    title: 'Pull Strings',
    year: '2026',
    rating: '0.0',
    seasons: 1,
    poster: 'https://media.homietv.com/file/all-asset-uploads/cm-app-media-two/tv-shows/2026-08-19/87irKQfNYW0HlOFXemvSMygDkvD.jpg',
    genres: ['Action & Adventure', 'Comedy', 'Sci-Fi & Fantasy'],
  ),
  Show(
    title: 'The Early Spring',
    year: '2026',
    rating: '0.0',
    seasons: 1,
    poster: 'https://media.homietv.com/file/all-asset-uploads/cm-app-media-two/tv-shows/2026-08-26/lGFngmJWMO4HTPcI0sUGKBAFqMe.jpg',
    genres: ['Drama'],
  ),
  Show(
    title: 'Our Happy Days',
    year: '2026',
    rating: '9.0',
    seasons: 4,
    poster: 'https://media.homietv.com/file/all-asset-uploads/cm-app-media-two/posters/2026-03-30/21-17-21-1.jpg',
    genres: ['Drama', 'Family'],
  ),
  Show(
    title: 'Family Register',
    year: '2026',
    rating: '8.9',
    seasons: 2,
    poster: 'https://media.homietv.com/file/all-asset-uploads/cm-app-media-two/tv-shows/2026-07-07/l1EoUpPABU7aqr6K2vt40ac0v7B.jpg',
    genres: ['Drama', 'Family'],
  ),
  Show(
    title: 'A Trap Called Desire',
    year: '2026',
    rating: '8.5',
    seasons: 1,
    poster: 'https://media.homietv.com/file/all-asset-uploads/cm-app-media-two/tv-shows/2026-08-11/repjdxPyA19x0ghyJFmECTDwGvj.jpg',
    genres: ['Crime', 'Drama', 'Mystery'],
  ),
  Show(
    title: 'New Recruit Season 4',
    year: '2026',
    rating: '8.5',
    seasons: 2,
    poster: 'https://media.homietv.com/file/all-asset-uploads/cm-app-media-two/posters/2026-08-26/02-04-52-73o2gn_4f.jpg',
    genres: ['Comedy', 'Drama'],
  ),
  Show(
    title: 'My Bias, My Boss',
    year: '2026',
    rating: '8.9',
    seasons: 1,
    poster: 'https://media.homietv.com/file/all-asset-uploads/cm-app-media-two/tv-shows/2026-08-03/A4Y4xlDHS4xi2WI9265vRyIYLoo.jpg',
    genres: ['Comedy', 'Drama'],
  ),
];
