import 'package:cm_app/core/models/movie.dart';

final mockMovies = <MediaItem>[
  MediaItem(
    id: 26039,
    title: 'Las Tres Sisters',
    slug: 'las-tres-sisters-cpxny6vp',
    year: '2025',
    poster: 'https://media.homietv.com/file/all-asset-uploads/cm-app-media-two/movies/2026-09-21/2b3LisgGMchU5MZPjrgsBh75Tjl.jpg',
    rating: '6.0',
    resolution: null,
    isAdult: '0',
    categories: const [
      MediaCategory(id: 4, tmdbGenreId: '35', name: 'Comedy'),
      MediaCategory(id: 7, tmdbGenreId: '18', name: 'Drama'),
    ],
    type: MediaType.movie,
    homietv: 1,
    ysflix: 0,
  ),

  MediaItem(
    id: 26027,
    title: 'Dirty Games',
    slug: 'dirty-games-rhcq79dt',
    year: '2026',
    poster: 'https://media.homietv.com/file/all-asset-uploads/cm-app-media-two/movies/2026-09-19/4fGPBV5sexQVYL9ViNbfLrPbTyD.jpg',
    rating: '8.0',
    resolution: null,
    isAdult: '0',
    categories: const [
      MediaCategory(id: 5, tmdbGenreId: '80', name: 'Crime'),
      MediaCategory(id: 17, tmdbGenreId: '53', name: 'Thriller'),
    ],
    type: MediaType.movie,
    homietv: 1,
    ysflix: 0,
  ),

  MediaItem(
    id: 26036,
    title: 'Edge of Tomorrow',
    slug: 'edge-of-tomorrow-33dlheyk',
    year: '2014',
    poster: 'https://media.homietv.com/file/all-asset-uploads/cm-app-media-two/movies/2026-09-20/nBM9MMa2WCwvMG4IJ3eiGUdbPe6.jpg',
    rating: '7.6',
    resolution: '4K',
    isAdult: '0',
    categories: const [
      MediaCategory(id: 1, tmdbGenreId: '28', name: 'Action'),
      MediaCategory(id: 15, tmdbGenreId: '878', name: 'Science Fiction'),
    ],
    type: MediaType.movie,
    homietv: 1,
    ysflix: 0,
  ),

  MediaItem(
    id: 26035,
    title: 'Deadlocked: Dad of the Dead',
    slug: 'deadlocked-dad-of-the-dead-fu7lb1wr',
    year: '2026',
    poster: 'https://media.homietv.com/file/all-asset-uploads/cm-app-media-two/movies/2026-09-20/gWeUbgZvrfbEFYra8omnqJQJZid.jpg',
    rating: '5.2',
    resolution: null,
    isAdult: '0',
    categories: const [
      MediaCategory(id: 4, tmdbGenreId: '35', name: 'Comedy'),
      MediaCategory(id: 11, tmdbGenreId: '27', name: 'Horror'),
      MediaCategory(id: 17, tmdbGenreId: '53', name: 'Thriller'),
    ],
    type: MediaType.movie,
    homietv: 1,
    ysflix: 0,
  ),

  MediaItem(
    id: 26034,
    title: 'The Last Scene (Aka) Öngörü',
    slug: 'the-last-scene-aka-ongoru-zw9up0gc',
    year: '2026',
    poster: 'https://media.homietv.com/file/all-asset-uploads/cm-app-media-two/movies/2026-09-20/vQ69OZWDZ90ktHcW2Ku01ht4eis.jpg',
    rating: '7.0',
    resolution: null,
    isAdult: '0',
    categories: const [
      MediaCategory(id: 7, tmdbGenreId: '18', name: 'Drama'),
      MediaCategory(id: 14, tmdbGenreId: '10749', name: 'Romance'),
    ],
    type: MediaType.movie,
    homietv: 1,
    ysflix: 0,
  ),

  MediaItem(
    id: 26033,
    title: 'The Last Class',
    slug: 'the-last-class-ntf6xwlv',
    year: '2025',
    poster: 'https://media.homietv.com/file/all-asset-uploads/cm-app-media-two/movies/2026-09-20/AaRXE0Dyu1wEHP2JLJ2IOGp3bWd.jpg',
    rating: '10.0',
    resolution: null,
    isAdult: '0',
    categories: const [
      MediaCategory(id: 6, tmdbGenreId: '99', name: 'Documentary'),
    ],
    type: MediaType.movie,
    homietv: 1,
    ysflix: 0,
  ),

  MediaItem(
    id: 26032,
    title: 'The Last Kiss',
    slug: 'the-last-kiss-lqcw0ifn',
    year: '2026',
    poster: 'https://media.homietv.com/file/all-asset-uploads/cm-app-media-two/movies/2026-09-20/cLZ7iFZc25vluSIKt3XtdSTait4.jpg',
    rating: '6.5',
    resolution: null,
    isAdult: '0',
    categories: const [
      MediaCategory(id: 11, tmdbGenreId: '27', name: 'Horror'),
      MediaCategory(id: 13, tmdbGenreId: '9648', name: 'Mystery'),
      MediaCategory(id: 17, tmdbGenreId: '53', name: 'Thriller'),
    ],
    type: MediaType.movie,
    homietv: 1,
    ysflix: 0,
  ),

  MediaItem(
    id: 26025,
    title: 'Kill Will',
    slug: 'kill-will-ba6bk8h2',
    year: '2026',
    poster: 'https://media.homietv.com/file/all-asset-uploads/cm-app-media-two/movies/2026-09-19/1tvDh9xFGuCyQ73bMeAH2FmU1ZN.jpg',
    rating: '4.8',
    resolution: null,
    isAdult: '0',
    categories: const [
      MediaCategory(id: 1, tmdbGenreId: '28', name: 'Action'),
      MediaCategory(id: 4, tmdbGenreId: '35', name: 'Comedy'),
      MediaCategory(id: 5, tmdbGenreId: '80', name: 'Crime'),
    ],
    type: MediaType.movie,
    homietv: 1,
    ysflix: 0,
  ),

  MediaItem(
    id: 26031,
    title: 'Johnny Keep Walking!',
    slug: 'johnny-keep-walking-r8i3dyiv',
    year: '2023',
    poster: 'https://media.homietv.com/file/all-asset-uploads/cm-app-media-two/movies/2026-09-19/8055dyA5XJbEcN9JjECZ1WsR62o.jpg',
    rating: '7.3',
    resolution: null,
    isAdult: '0',
    categories: const [
      MediaCategory(id: 4, tmdbGenreId: '35', name: 'Comedy'),
      MediaCategory(id: 7, tmdbGenreId: '18', name: 'Drama'),
    ],
    type: MediaType.movie,
    homietv: 1,
    ysflix: 0,
  ),

  MediaItem(
    id: 26024,
    title: 'Time Still Turns the Pages',
    slug: 'time-still-turns-the-pages-4wweszyv',
    year: '2023',
    poster: 'https://media.homietv.com/file/all-asset-uploads/cm-app-media-two/posters/2026-09-19/01-26-07-z8YSragPkquUKcTTITuMcEQ1PKa.jpg',
    rating: '7.8',
    resolution: null,
    isAdult: '0',
    categories: const [MediaCategory(id: 7, tmdbGenreId: '18', name: 'Drama')],
    type: MediaType.movie,
    homietv: 1,
    ysflix: 0,
  ),

  MediaItem(
    id: 26026,
    title: 'One of the Good Ones',
    slug: 'one-of-the-good-ones-dpod5jfz',
    year: '2026',
    poster: 'https://media.homietv.com/file/all-asset-uploads/cm-app-media-two/movies/2026-09-19/zuAzDGV3mSRpW0sZaZkexL2phx1.jpg',
    rating: '5.5',
    resolution: null,
    isAdult: '0',
    categories: const [
      MediaCategory(id: 4, tmdbGenreId: '35', name: 'Comedy'),
      MediaCategory(id: 7, tmdbGenreId: '18', name: 'Drama'),
    ],
    type: MediaType.movie,
    homietv: 1,
    ysflix: 0,
  ),

  MediaItem(
    id: 26030,
    title: 'Bad Counselors',
    slug: 'bad-counselors-hbp4zyi7',
    year: '2026',
    poster: 'https://media.homietv.com/file/all-asset-uploads/cm-app-media-two/movies/2026-09-19/raWg26WVDQeqbTizRjdgJpCHssd.jpg',
    rating: '8.5',
    resolution: null,
    isAdult: '0',
    categories: const [MediaCategory(id: 4, tmdbGenreId: '35', name: 'Comedy')],
    type: MediaType.movie,
    homietv: 1,
    ysflix: 0,
  ),

  MediaItem(
    id: 26029,
    title: 'Shark Frenzy',
    slug: 'shark-frenzy-p0fsopiw',
    year: '2026',
    poster: 'https://media.homietv.com/file/all-asset-uploads/cm-app-media-two/movies/2026-09-19/A1dZIibysmc8fi5W4q18oJ2aSo4.jpg',
    rating: '7.0',
    resolution: null,
    isAdult: '0',
    categories: const [
      MediaCategory(id: 1, tmdbGenreId: '28', name: 'Action'),
      MediaCategory(id: 11, tmdbGenreId: '27', name: 'Horror'),
      MediaCategory(id: 17, tmdbGenreId: '53', name: 'Thriller'),
    ],
    type: MediaType.movie,
    homietv: 1,
    ysflix: 0,
  ),

  MediaItem(
    id: 26028,
    title: 'Norton Creek Massacre',
    slug: 'norton-creek-massacre-6loxqdmm',
    year: '2026',
    poster: 'https://media.homietv.com/file/all-asset-uploads/cm-app-media-two/movies/2026-09-19/3QT48s1TJmUrH32fpUKLP7AO7hz.jpg',
    rating: '5.0',
    resolution: null,
    isAdult: '0',
    categories: const [
      MediaCategory(id: 11, tmdbGenreId: '27', name: 'Horror'),
    ],
    type: MediaType.movie,
    homietv: 1,
    ysflix: 0,
  ),

  MediaItem(
    id: 26003,
    title: 'Anaconda: Cursed Jungle',
    slug: 'anaconda-87bqvfpg',
    year: '2024',
    poster: 'https://media.homietv.com/file/all-asset-uploads/cm-app-media-two/movies/2026-09-17/pPfsEXzfk2URkQ1OxhUShAXdxMr.jpg',
    rating: '7.1',
    resolution: null,
    isAdult: '0',
    categories: const [
      MediaCategory(id: 2, tmdbGenreId: '12', name: 'Adventure'),
      MediaCategory(id: 11, tmdbGenreId: '27', name: 'Horror'),
    ],
    type: MediaType.movie,
    homietv: 1,
    ysflix: 0,
  ),

  MediaItem(
    id: 26023,
    title: 'Give You A Candy',
    slug: 'give-you-a-candy-vbcnrd14',
    year: '2026',
    poster: 'https://media.homietv.com/file/all-asset-uploads/cm-app-media-two/movies/2026-09-19/dEBGIgF3mjHHEozd2VMcrbTP6g1.jpg',
    rating: '6.7',
    resolution: null,
    isAdult: '0',
    categories: const [
      MediaCategory(id: 7, tmdbGenreId: '18', name: 'Drama'),
      MediaCategory(id: 8, tmdbGenreId: '10751', name: 'Family'),
    ],
    type: MediaType.movie,
    homietv: 1,
    ysflix: 0,
  ),

  MediaItem(
    id: 26022,
    title: 'Teenage Sex and Death at Camp Miasma',
    slug: 'teenage-sex-and-death-at-camp-miasma-daw8ehff',
    year: '2026',
    poster: 'https://media.homietv.com/file/all-asset-uploads/cm-app-media-two/movies/2026-09-18/rGzlBlz9A7seUUTZp5k68A4IDvm.jpg',
    rating: '6.7',
    resolution: null,
    isAdult: '0',
    categories: const [
      MediaCategory(id: 4, tmdbGenreId: '35', name: 'Comedy'),
      MediaCategory(id: 11, tmdbGenreId: '27', name: 'Horror'),
      MediaCategory(id: 14, tmdbGenreId: '10749', name: 'Romance'),
    ],
    type: MediaType.movie,
    homietv: 1,
    ysflix: 0,
  ),
];
