import 'package:cm_app/core/models/movie.dart';

// ============================================================
// MOCK DATA
// ============================================================

const trendingMovies = <MediaItem>[
  MediaItem(
    id: 26022,
    title: 'Teenage Sex and Death at Camp Miasma',
    slug: 'teenage-sex-and-death-at-camp-miasma-daw8ehff',
    year: '2026',
    poster: 'https://media.homietv.com/file/all-asset-uploads/cm-app-media-two/movies/2026-09-18/rGzlBlz9A7seUUTZp5k68A4IDvm.jpg',
    rating: '6.7',
    resolution: null,
    isAdult: '0',
    categories: [
      MediaCategory(id: 4, tmdbGenreId: '35', name: 'Comedy'),
      MediaCategory(id: 11, tmdbGenreId: '27', name: 'Horror'),
      MediaCategory(id: 14, tmdbGenreId: '10749', name: 'Romance'),
    ],
    type: MediaType.movie,
    homietv: 1,
    ysflix: 0,
  ),
  MediaItem(
    id: 26019,
    title: 'Lust Stories 3',
    slug: 'lust-stories-3-biopcp4z',
    year: '2026',
    poster: 'https://media.homietv.com/file/all-asset-uploads/cm-app-media-two/movies/2026-09-18/1GBe4TeCeXa1ENg0rv2JH8cH0ry.jpg',
    rating: '0.0',
    resolution: '4K',
    isAdult: '0',
    categories: [
      MediaCategory(id: 7, tmdbGenreId: '18', name: 'Drama'),
      MediaCategory(id: 14, tmdbGenreId: '10749', name: 'Romance'),
    ],
    type: MediaType.movie,
    homietv: 1,
    ysflix: 0,
  ),
  MediaItem(
    id: 26014,
    title: 'Thudakkam',
    slug: 'thudakkam-ewk3abf6',
    year: '2026',
    poster: 'https://media.homietv.com/file/all-asset-uploads/cm-app-media-two/movies/2026-09-18/A8Y0QLNqaFvsergQe80tC6Nfa2k.jpg',
    rating: '5.5',
    resolution: null,
    isAdult: '0',
    categories: [
      MediaCategory(id: 1, tmdbGenreId: '28', name: 'Action'),
      MediaCategory(id: 7, tmdbGenreId: '18', name: 'Drama'),
    ],
    type: MediaType.movie,
    homietv: 1,
    ysflix: 0,
  ),
  MediaItem(
    id: 26011,
    title: 'Irumudi',
    slug: 'irumudi-c0wncyjx',
    year: '2026',
    poster: 'https://media.homietv.com/file/all-asset-uploads/cm-app-media-two/movies/2026-09-18/sPePQmJRKkB14sGjB7zBkLJkaTW.jpg',
    rating: '6.6',
    resolution: '4K',
    isAdult: '0',
    categories: [
      MediaCategory(id: 1, tmdbGenreId: '28', name: 'Action'),
      MediaCategory(id: 7, tmdbGenreId: '18', name: 'Drama'),
      MediaCategory(id: 8, tmdbGenreId: '10751', name: 'Family'),
    ],
    type: MediaType.movie,
    homietv: 1,
    ysflix: 0,
  ),
  MediaItem(
    id: 26006,
    title: 'Polong',
    slug: 'polong-d7qf3vra',
    year: '2026',
    poster: 'https://media.homietv.com/file/all-asset-uploads/cm-app-media-two/movies/2026-09-17/6bjfKoJB3dVwGfAtDefVVuSrZOU.jpg',
    rating: '8.6',
    resolution: null,
    isAdult: '0',
    categories: [
      MediaCategory(id: 11, tmdbGenreId: '27', name: 'Horror'),
      MediaCategory(id: 13, tmdbGenreId: '9648', name: 'Mystery'),
      MediaCategory(id: 17, tmdbGenreId: '53', name: 'Thriller'),
    ],
    type: MediaType.movie,
    homietv: 1,
    ysflix: 0,
  ),
];

const trendingTvShows = <MediaItem>[
  MediaItem(
    id: 5183,
    title: 'Lanterns',
    slug: 'lanterns-rz11pbmz',
    year: '2026',
    poster: 'https://media.homietv.com/file/all-asset-uploads/cm-app-media-two/tv-shows/2026-08-17/rb94rKVIzLyfWufIN7WqLvadBDH.jpg',
    rating: '6.8',
    resolution: '4K',
    isAdult: '0',
    categories: [
      MediaCategory(id: 1, tmdbGenreId: '10759', name: 'Action & Adventure'),
      MediaCategory(id: 9, tmdbGenreId: '9648', name: 'Mystery'),
      MediaCategory(id: 12, tmdbGenreId: '10765', name: 'Sci-Fi & Fantasy'),
    ],
    type: MediaType.tvShow,
    homietv: 1,
    ysflix: 0,
  ),
  MediaItem(
    id: 5113,
    title: 'Love on the Menu',
    slug: 'love-on-the-menu-ykiuckme',
    year: '2026',
    poster: 'https://media.homietv.com/file/all-asset-uploads/cm-app-media-two/tv-shows/2026-07-26/pGEz6J7GFT0LXGBd6ZSHvJtTsAS.jpg',
    rating: '8.5',
    resolution: null,
    isAdult: '0',
    categories: [
      MediaCategory(id: 6, tmdbGenreId: '18', name: 'Drama'),
      MediaCategory(id: 7, tmdbGenreId: '10751', name: 'Family'),
    ],
    type: MediaType.tvShow,
    homietv: 1,
    ysflix: 0,
  ),
  MediaItem(
    id: 5231,
    title: 'A Love Other Than Yours',
    slug: 'a-love-other-than-yours-gathwdch',
    year: '2026',
    poster: 'https://media.homietv.com/file/all-asset-uploads/cm-app-media-two/posters/2026-09-12/08-28-55-1.jpg',
    rating: '8.9',
    resolution: null,
    isAdult: '0',
    categories: [
      MediaCategory(id: 3, tmdbGenreId: '35', name: 'Comedy'),
      MediaCategory(id: 6, tmdbGenreId: '18', name: 'Drama'),
    ],
    type: MediaType.tvShow,
    homietv: 1,
    ysflix: 0,
  ),
  MediaItem(
    id: 5207,
    title: 'Four Hands, Two Sonatas',
    slug: 'four-hands-two-sonatas-1t4n8tru',
    year: '2026',
    poster: 'https://media.homietv.com/file/all-asset-uploads/cm-app-media-two/posters/2026-08-29/11-13-33-4.jpg',
    rating: '8.9',
    resolution: null,
    isAdult: '0',
    categories: [MediaCategory(id: 6, tmdbGenreId: '18', name: 'Drama')],
    type: MediaType.tvShow,
    homietv: 1,
    ysflix: 0,
  ),
  MediaItem(
    id: 5109,
    title: 'Stuart Fails to Save the Universe',
    slug: 'stuart-fails-to-save-the-universe-swr3hcic',
    year: '2026',
    poster: 'https://media.homietv.com/file/all-asset-uploads/cm-app-media-two/tv-shows/2026-07-24/iQbTbwmLX5Nh1nlH21YUJPWt3Zo.jpg',
    rating: '9.0',
    resolution: null,
    isAdult: '0',
    categories: [
      MediaCategory(id: 3, tmdbGenreId: '35', name: 'Comedy'),
      MediaCategory(id: 12, tmdbGenreId: '10765', name: 'Sci-Fi & Fantasy'),
    ],
    type: MediaType.tvShow,
    homietv: 1,
    ysflix: 0,
  ),
];
