import 'package:cm_app/core/models/movie.dart';
import 'package:cm_app/core/models/tv_show.dart';

final mockTvShows = <TvShowItem>[
  TvShowItem(
    id: 4845,
    title: "Stranger Things: Tales from '85",
    slug: 'stranger-things-tales-from-85-oez6qopa',
    year: '2026',
    poster: 'https://media.homietv.com/file/all-asset-uploads/cm-app-media-two/tv-shows/2026-04-23/2orq3F4a1prP3RnJjYSWzSjHYZQ.jpg',
    rating: '6.5',
    resolution: null,
    isAdult: '0',
    categories: const [
      MediaCategory(id: 1, tmdbGenreId: '10759', name: 'Action & Adventure'),
      MediaCategory(id: 2, tmdbGenreId: '16', name: 'Animation'),
      MediaCategory(id: 9, tmdbGenreId: '9648', name: 'Mystery'),
      MediaCategory(id: 12, tmdbGenreId: '10765', name: 'Sci-Fi & Fantasy'),
    ],
    seasons: 2,
    type: MediaType.tvShow,
    homietv: 1,
    ysflix: 0,
  ),

  TvShowItem(
    id: 5254,
    title: 'Queen of Ambition',
    slug: 'queen-of-ambition-qbghlgjw',
    year: '2013',
    poster: 'https://media.homietv.com/file/all-asset-uploads/cm-app-media-two/posters/2026-09-21/11-39-44-1.webp',
    rating: '6.8',
    resolution: null,
    isAdult: '0',
    categories: const [MediaCategory(id: 6, tmdbGenreId: '18', name: 'Drama')],
    seasons: 1,
    type: MediaType.tvShow,
    homietv: 1,
    ysflix: 0,
  ),

  TvShowItem(
    id: 5183,
    title: 'Lanterns',
    slug: 'lanterns-rz11pbmz',
    year: '2026',
    poster: 'https://media.homietv.com/file/all-asset-uploads/cm-app-media-two/tv-shows/2026-08-17/rb94rKVIzLyfWufIN7WqLvadBDH.jpg',
    rating: '6.8',
    resolution: '4K',
    isAdult: '0',
    categories: const [
      MediaCategory(id: 1, tmdbGenreId: '10759', name: 'Action & Adventure'),
      MediaCategory(id: 9, tmdbGenreId: '9648', name: 'Mystery'),
      MediaCategory(id: 12, tmdbGenreId: '10765', name: 'Sci-Fi & Fantasy'),
    ],
    seasons: 1,
    type: MediaType.tvShow,
    homietv: 1,
    ysflix: 0,
  ),

  TvShowItem(
    id: 5113,
    title: 'Love on the Menu',
    slug: 'love-on-the-menu-ykiuckme',
    year: '2026',
    poster: 'https://media.homietv.com/file/all-asset-uploads/cm-app-media-two/tv-shows/2026-07-26/pGEz6J7GFT0LXGBd6ZSHvJtTsAS.jpg',
    rating: '8.5',
    resolution: null,
    isAdult: '0',
    categories: const [
      MediaCategory(id: 6, tmdbGenreId: '18', name: 'Drama'),
      MediaCategory(id: 7, tmdbGenreId: '10751', name: 'Family'),
    ],
    seasons: 1,
    type: MediaType.tvShow,
    homietv: 1,
    ysflix: 0,
  ),

  TvShowItem(
    id: 5218,
    title: 'Fairway of Love',
    slug: 'fairway-of-love-d9z94vqi',
    year: '2026',
    poster: 'https://media.homietv.com/file/all-asset-uploads/cm-app-media-two/tv-shows/2026-09-06/deHIDwrFpxqYylquqeN1ITalWwX.jpg',
    rating: '0.0',
    resolution: null,
    isAdult: '0',
    categories: const [MediaCategory(id: 6, tmdbGenreId: '18', name: 'Drama')],
    seasons: 2,
    type: MediaType.tvShow,
    homietv: 1,
    ysflix: 0,
  ),

  TvShowItem(
    id: 5181,
    title: 'LOVEx3',
    slug: 'lovex3-driu7ajb',
    year: '2026',
    poster: 'https://media.homietv.com/file/all-asset-uploads/cm-app-media-two/tv-shows/2026-08-16/cTbYyfSllAHAqi4j59ap0sTf0rU.jpg',
    rating: '0.0',
    resolution: null,
    isAdult: '0',
    categories: const [MediaCategory(id: 6, tmdbGenreId: '18', name: 'Drama')],
    seasons: 1,
    type: MediaType.tvShow,
    homietv: 1,
    ysflix: 0,
  ),

  TvShowItem(
    id: 5115,
    title: 'Match Point',
    slug: 'match-point-2r8pu7e5',
    year: '2026',
    poster: 'https://media.homietv.com/file/all-asset-uploads/cm-app-media-two/tv-shows/2026-07-26/1p9nljBwKxGVyjhEITcZ8MxOIO3.jpg',
    rating: '0.0',
    resolution: null,
    isAdult: '0',
    categories: const [MediaCategory(id: 6, tmdbGenreId: '18', name: 'Drama')],
    seasons: 1,
    type: MediaType.tvShow,
    homietv: 1,
    ysflix: 0,
  ),

  TvShowItem(
    id: 5231,
    title: 'A Love Other Than Yours',
    slug: 'a-love-other-than-yours-gathwdch',
    year: '2026',
    poster: 'https://media.homietv.com/file/all-asset-uploads/cm-app-media-two/posters/2026-09-12/08-28-55-1.jpg',
    rating: '8.9',
    resolution: null,
    isAdult: '0',
    categories: const [
      MediaCategory(id: 3, tmdbGenreId: '35', name: 'Comedy'),
      MediaCategory(id: 6, tmdbGenreId: '18', name: 'Drama'),
    ],
    seasons: 1,
    type: MediaType.tvShow,
    homietv: 1,
    ysflix: 0,
  ),

  TvShowItem(
    id: 5207,
    title: 'Four Hands, Two Sonatas',
    slug: 'four-hands-two-sonatas-1t4n8tru',
    year: '2026',
    poster: 'https://media.homietv.com/file/all-asset-uploads/cm-app-media-two/posters/2026-08-29/11-13-33-4.jpg',
    rating: '8.9',
    resolution: null,
    isAdult: '0',
    categories: const [MediaCategory(id: 6, tmdbGenreId: '18', name: 'Drama')],
    seasons: 1,
    type: MediaType.tvShow,
    homietv: 1,
    ysflix: 0,
  ),

  TvShowItem(
    id: 5253,
    title: '行镖',
    slug: 'xing-biao-pekyekhu',
    year: '2026',
    poster: 'https://media.homietv.com/file/all-asset-uploads/cm-app-media-two/posters/2026-09-20/19-01-38-photo_2026-09-20_19-17-45.jpg',
    rating: '0.0',
    resolution: null,
    isAdult: '0',
    categories: const [],
    seasons: 1,
    type: MediaType.tvShow,
    homietv: 1,
    ysflix: 0,
  ),

  TvShowItem(
    id: 4501,
    title: 'Renegade Immortal',
    slug: 'renegade-immortal-y0l5n5us',
    year: '2023',
    poster: 'https://media.homietv.com/file/all-asset-uploads/cm-app-media-two/tv-shows/2026-01-08/6AVM12M6UunFmX0bSmP2o4N5Bnt.jpg',
    rating: '8.7',
    resolution: null,
    isAdult: '0',
    categories: const [
      MediaCategory(id: 1, tmdbGenreId: '10759', name: 'Action & Adventure'),
      MediaCategory(id: 2, tmdbGenreId: '16', name: 'Animation'),
      MediaCategory(id: 6, tmdbGenreId: '18', name: 'Drama'),
      MediaCategory(id: 12, tmdbGenreId: '10765', name: 'Sci-Fi & Fantasy'),
    ],
    seasons: 7,
    type: MediaType.tvShow,
    homietv: 1,
    ysflix: 1,
  ),

  TvShowItem(
    id: 5228,
    title: 'Against the Current',
    slug: 'against-the-current-zvjt4p5f',
    year: '2026',
    poster: 'https://media.homietv.com/file/all-asset-uploads/cm-app-media-two/tv-shows/2026-09-11/hGQTmpChpuuZe7SKYdaUOsVtdJE.jpg',
    rating: '0.0',
    resolution: null,
    isAdult: '0',
    categories: const [
      MediaCategory(id: 6, tmdbGenreId: '18', name: 'Drama'),
      MediaCategory(id: 7, tmdbGenreId: '10751', name: 'Family'),
    ],
    seasons: 1,
    type: MediaType.tvShow,
    homietv: 1,
    ysflix: 0,
  ),

  TvShowItem(
    id: 4995,
    title: 'Kaeo Phitsadan',
    slug: 'kaeo-phitsadan-2026-cdipxjgu',
    year: '2026',
    poster: 'https://media.homietv.com/file/all-asset-uploads/cm-app-media-two/posters/2026-06-06/15-06-01-3o66pm_4f.jpg',
    rating: '0.0',
    resolution: null,
    isAdult: '0',
    categories: const [
      MediaCategory(id: 1, tmdbGenreId: '10759', name: 'Action & Adventure'),
      MediaCategory(id: 6, tmdbGenreId: '18', name: 'Drama'),
    ],
    seasons: 1,
    type: MediaType.tvShow,
    homietv: 1,
    ysflix: 0,
  ),

  TvShowItem(
    id: 5242,
    title: 'Spring of the Blade',
    slug: 'spring-of-the-blade-hgvgda9v',
    year: '2026',
    poster: 'https://media.homietv.com/file/all-asset-uploads/cm-app-media-two/tv-shows/2026-09-17/uRWqHI4R4nOSPpRnbr8JjnpCmgx.jpg',
    rating: '0.0',
    resolution: null,
    isAdult: '0',
    categories: const [
      MediaCategory(id: 6, tmdbGenreId: '18', name: 'Drama'),
      MediaCategory(id: 7, tmdbGenreId: '10751', name: 'Family'),
    ],
    seasons: 1,
    type: MediaType.tvShow,
    homietv: 1,
    ysflix: 0,
  ),

  TvShowItem(
    id: 5237,
    title: "A Parasite's Heart",
    slug: 'a-parasites-heart-555bjv6t',
    year: '2026',
    poster: 'https://media.homietv.com/file/all-asset-uploads/cm-app-media-two/tv-shows/2026-09-14/wHVoF7ykBtHpwNhKQtT7aVVOjzw.jpg',
    rating: '0.0',
    resolution: null,
    isAdult: '0',
    categories: const [MediaCategory(id: 6, tmdbGenreId: '18', name: 'Drama')],
    seasons: 1,
    type: MediaType.tvShow,
    homietv: 1,
    ysflix: 0,
  ),

  TvShowItem(
    id: 5091,
    title: 'Fill The Beat',
    slug: 'fill-the-beat-vmilcm3l',
    year: '2026',
    poster: 'https://media.homietv.com/file/all-asset-uploads/cm-app-media-two/posters/2026-07-13/01-04-25-images.jpg',
    rating: '0.0',
    resolution: null,
    isAdult: '0',
    categories: const [MediaCategory(id: 6, tmdbGenreId: '18', name: 'Drama')],
    seasons: 1,
    type: MediaType.tvShow,
    homietv: 1,
    ysflix: 0,
  ),

  TvShowItem(
    id: 5209,
    title: 'Mr. Fanboy',
    slug: 'mr-fanboy-act9uwcb',
    year: '2026',
    poster: 'https://media.homietv.com/file/all-asset-uploads/cm-app-media-two/tv-shows/2026-08-30/vNo2ik8L1NdlgKdV2MJzU3mYKLV.jpg',
    rating: '0.0',
    resolution: null,
    isAdult: '0',
    categories: const [MediaCategory(id: 6, tmdbGenreId: '18', name: 'Drama')],
    seasons: 1,
    type: MediaType.tvShow,
    homietv: 1,
    ysflix: 0,
  ),

  TvShowItem(
    id: 5109,
    title: 'Stuart Fails to Save the Universe',
    slug: 'stuart-fails-to-save-the-universe-swr3hcic',
    year: '2026',
    poster: 'https://media.homietv.com/file/all-asset-uploads/cm-app-media-two/tv-shows/2026-07-24/iQbTbwmLX5Nh1nlH21YUJPWt3Zo.jpg',
    rating: '9.0',
    resolution: null,
    isAdult: '0',
    categories: const [
      MediaCategory(id: 3, tmdbGenreId: '35', name: 'Comedy'),
      MediaCategory(id: 12, tmdbGenreId: '10765', name: 'Sci-Fi & Fantasy'),
    ],
    seasons: 1,
    type: MediaType.tvShow,
    homietv: 1,
    ysflix: 0,
  ),

  TvShowItem(
    id: 4354,
    title: 'Star Trek: Strange New Worlds',
    slug: 'star-trek-strange-new-worlds-ppvblen9',
    year: '2022',
    poster: 'https://media.homietv.com/file/all-asset-uploads/cm-app-media-two/tv-shows/2025-11-12/w6KapI2JvrCkOPmQhkwYPJNjqeo.jpg',
    rating: '8.0',
    resolution: null,
    isAdult: '0',
    categories: const [
      MediaCategory(id: 6, tmdbGenreId: '18', name: 'Drama'),
      MediaCategory(id: 12, tmdbGenreId: '10765', name: 'Sci-Fi & Fantasy'),
    ],
    seasons: 2,
    type: MediaType.tvShow,
    homietv: 1,
    ysflix: 0,
  ),

  TvShowItem(
    id: 5126,
    title: 'Heartless City// Cruel City',
    slug: 'heartless-city-ysq1ob8y',
    year: '2013',
    poster: 'https://media.homietv.com/file/all-asset-uploads/cm-app-media-two/posters/2026-09-19/23-53-49-1.jpg',
    rating: '8.9',
    resolution: null,
    isAdult: '0',
    categories: const [
      MediaCategory(id: 1, tmdbGenreId: '10759', name: 'Action & Adventure'),
      MediaCategory(id: 4, tmdbGenreId: '80', name: 'Crime'),
      MediaCategory(id: 6, tmdbGenreId: '18', name: 'Drama'),
    ],
    seasons: 1,
    type: MediaType.tvShow,
    homietv: 1,
    ysflix: 0,
  ),
];
