name: cm_app
description: "Channel Myanmar WebSoup"
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 3.0.0
repository: https://github.com/ThanCoder/cm_app

environment:
  sdk: ^3.13.0

dependencies:
  cupertino_icons: ^1.0.9
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0
  t_html_parser: ^1.5.0
  crypto: ^3.0.7
  path_provider: ^2.1.6
  package_info_plus: ^10.2.1
  window_manager: ^0.5.2

  dart_core_extensions:
    git:
      url: https://github.com/ThanCoder/dart_core_extensions.git
  t_widgets:
    git:
      url: https://github.com/ThanCoder/t_widgets.git
  t_client:
    git:
      url: https://github.com/ThanCoder/t_client
  cfb_store: ^0.7.0
  # flutter pub upgrade dart_core_extensions t_widgets t_client

dev_dependencies:
  # dart run change_app_package_name:main [com.new.package.name]
  change_app_package_name: ^1.5.0
  # dart run flutter_launcher_icons
  flutter_launcher_icons: ^0.14.4

  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:

  android: "launcher_icon"
  image_path: "assets/logo/logo_2.jpg"
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/logo/
  - CHANGELOG.md
  - README.md
  - pubspec.yaml
